version: '3.5'
services:
  db:
    container_name: msv-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'msv'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    tty: true
    restart: on-failure
  web:
    build: ./docker
    image: jeffersonassilva/php74-mysql-apache
    container_name: msv
    working_dir: /var/www/html/msv
    ports:
      - 8100:80
    volumes:
      - .:/var/www/html/msv
      - ./docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    entrypoint: [ "/bin/sh" , "/var/www/html/msv/docker/entrypoint.sh" ]
    command: apache2-foreground
    links:
      - db
    depends_on:
      - db
    tty: true
    restart: on-failure
